# Site settings
title: Herbal3d
name: Herbal3d
email: herbal3d@misterblue.com
description: > # this means to ignore newlines until "baseurl:"
    Herbal3d: Virtual and Augmented World Viewer Infrastructure

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://herbal3d.github.io" # the base hostname & protocol for your site

# twitter_username: misterblue
github_username:  herbal3d

# Set this to your UA-# value, or '' to disable the block completely
# gaaccount: 'UA-11111111-1'

permalink: /:year/:year-:month-:day-:title
pageinate: 5

highlighter: rogue
markdown: karmdown
gems:
    - jekyll-paginate
encoding: utf-8

excerpt_separator: <!-- more -->

exclude: ['README.md', 'LICENSE']
