# Site settings
title: Herbal3D Virtual Reality and Augmented Reality Viewer
email: herbal3d@misterblue.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://herbal3d.github.io" # the base hostname & protocol for your site

# twitter_username: jekyllrb
github_username:  herbal3d

# Build settings
markdown: kramdown
